### ISSUE TITLE
Realativa vs. absoluta länkar

### ISSUE THREAD

**Issue by 1dv450** [juhaniaa/ja222qm-webbramverk-api#1]
Du använder relativa länkar i svaren i ditt API. Det kan ifrågasättas av vissa och är ofta en debatt. I många fall brukar det funka utmärkt med relativa länkar medan andra hävdar att man bör ha absoluta länkar för att slippa låta klienten bygga ihop länkarna med en basURLl.

**Comment by juhaniaa** [comment]
:+1: relativa länkar känns mer naturligt men noterar detta
