### ISSUE TITLE
GET /hunters

### ISSUE THREAD

**Issue by 1dv450** [juhaniaa/ja222qm-webbramverk-api#2]
Denna kan ge väldigt mycket data då den nästlar in alla event som i sig nästlar in hunter igen. Inga större problem i ditt fall men skulle man jobba med mer data och komplexare objekt kan detta snabbt växa och bli ett stort dokument.

**Comment by juhaniaa** [comment]
noterar detta, tänkte att det kunde vara en bra sak att ha med, men kanske borde minska på om storlekent blir ett problem
