### ISSUE TITLE
Två Authorization-fält i headern

### ISSUE THREAD

**Issue by 1dv450** [juhaniaa/ja222qm-webbramverk-api#4]
När man gör anrop som kräver inloggning har du två Authorization headers, en för API-nycklen och en för din JWT. Känns lite underligt med två sådana fält. Då API-nyklen inte har något med aktorisering att göra tycker jag att det fältet borde heta något annat så man inte förvirrar och blandar ihop dem. Nu funkar det onekligen ändå men känns lite lurigt.

**Comment by juhaniaa** [comment]
API-nyckelns implementationen har jag fått från en av rails castsen som du länkade till men nu har jag iaf fixat så att jwt-tokenet har en egen header.
