### ISSUE TITLE
Sammanfattande kommentar

### ISSUE THREAD

**Issue by 1dv450** [juhaniaa/ja222qm-webbramverk-api#8]
Bra uppdelning av de olika applikationer i koden. Kul att du testat RABL i vyerna! Funktionerna som skulle finna finns med. Kanske kolla över lite mer med felhantering och statuskoder till klienten. Viss implementation är direkt tagen från mina exempel och därför har du även med lite överflödig kod. Kolla igenom det lite och se framförallt till att du förstör teorin till den muntliga examinationen. Annars tycker jag det är bra. Kanske lite mer beskrivande text i din readme om ditt API att det är tänkt som ett jakt-api. Gör det enklare att förstå de olika sakerna.

**Comment by juhaniaa** [comment]
Tack för kommentarer! Gillade RABL och hur det fungerade, men tyckte att just det där med statuskoder var svårt att hitta hur man skulle lösa i samband med deras templates.
